sudo: false

language: python

cache:
    directories:
        - $HOME/.cache/pip

branches:
    only:
        - master
        - b-0.2

dist: bionic

python:
    - "3.7"
    
services:
    - docker
    
before_install:
    - pip install --upgrade pip
    - pip install --upgrade setuptools
    - pip install --upgrade wheel
    - docker run --name postgres -e POSTGRES_PASSWORD=postgres -p 127.0.0.1:5432:5432 -d mdillon/postgis

install:
    - pip install -e .[tests,docs]

script:
    - ./run-test.sh

after_success:
    - coveralls
